# Generated by Django 3.2.2 on 2021-11-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='volume_por_ano',
            field=models.FloatField(default=10000),
        ),
    ]
