# Generated by Django 3.2.2 on 2021-07-02 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_registro_peso_calc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='id_godroid',
            new_name='id',
        ),
    ]
