# Generated by Django 3.2.2 on 2021-12-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_registro_volume_por_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='peso',
            field=models.FloatField(default=0),
        ),
    ]
