# Generated by Django 3.2.2 on 2021-06-10 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210609_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakdown',
            name='name',
        ),
    ]
