# Generated by Django 3.2.2 on 2021-06-10 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_breakdown_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('price', models.FloatField()),
                ('calc_price', models.FloatField()),
                ('productiontype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productiontype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
