# Generated by Django 3.2.2 on 2021-06-10 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_input'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Input',
            new_name='ProductionInput',
        ),
    ]
